### ISSUE TITLE
Namespaced `odoo` package

### ISSUE THREAD

**Issue by blaggacao** [xoe-labs/dodoo-migrator#2]
@sbidoul Might I ask you to kindly verify, if I'm getting the name spaced module stuff right, here?
https://github.com/xoe-labs/click-odoo-migrator/tree/master/src/odoo

The idea is that I can just write migrations scripts like `from odoo import migration` in migration scripts.
But I'm not sure if I need to import this odoo module when `__main__` is run or if the `__init__.py` is enough, also in case the script is run as `__main__`.

Thanks a lot in advance for your help! :wink:

**Comment by sbidoul** [comment]
Don't do this. Contrarily to `odoo.addons`, `odoo` is not designed to be an extensible namespace. At best you'll risk conflicts with Odoo names.

**Comment by blaggacao** [comment]
@sbidoul but Odoo would have registered this library at this location in their original PR upstream. So I don't think at least it easily brakes things. Are there other side effects I might not be aware of?

**Comment by blaggacao** [comment]
Easy workaround: it works only on python 3. (as the very odoo scripts themselves probably does).

Other practical workaround: dodoo-migrator will only see gaining momentum in py3 supported versions. :)
